version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: carpet_postgres
    restart: always
    environment:
      POSTGRES_USER: carpet
      POSTGRES_PASSWORD: carpet
      POSTGRES_DB: carpet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: carpet_adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres_data:
